---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgB4Pkp8PKkNcnZeDhvB+w7puRQVTkYCxW5vBMzmV5r9bNX87tcNAQOz3udxxluo0dduTEyaPv95tDVr9rTaAx7+MC9Wm/JRXnjJZqPM+tQLpHWv/V3iYUw61/EJF4bEgF3jsO4kCmz+AiiW/wiTLj6zFCw+1XatTYxbwqgCuLNB/rTG+o15Bt9rDE46bEidB68URf0N18FYK9q70t0ZyGhLYaWybVduMv2DNY5CtWsylFHNt4UyOg3h+RJfnpP516nDzs8KJqZYqCVJVwgOhWmEEGTqInROMoQPwIhr8obOs8vucpUHz5t3xLuTT8ohetPi58NYrS7kagReI0ELi1+t5vYub9gn5WiiOnZAFSfU2cMdrvb6goBUGFFvqysKZeuY14mqdrgX2x5V7UZH+d2Vx9KmP8+2rLdBuOWlWP0QIQtooWZcAV09S+GQ+5rq/kOqSb43CIA/Rtrg/iV03hm9zAAMSQ49Wa2HeYmbUf/As//eQysKQKe+AzyrcthphYkZzPOZW5rZYGfLI25MLJQGzcL0M/Sf1qeoZ8AJwOv8CVWE/IPli15QI/pH/E3eHhHVt1KzdhY4s1iZnFukArS/zcpIxD64YCzSE3xYxKmwvtWC4z/r+73UkG18KuTyGTv8qim1zM2Siz+IKw6s1RBmRpErDwOXErGPu2vBP3MiBhWFts6CIEkZjAfgpOX5aub9+8isx5qX/g==
    username: AgAjajFsWOEYLC7AuEFXSw8WZzYmU/sRtr/POtDBNe+B5x5nJwSDUzbeTithEG0XqP5evGqviquol1N5nocdTG6gPydUbucpCNefdjF1rFogeM92Lw3OHRc/g9ztmnHNXXnPoUWZvWq9u2ooFwjdnk0BhOa7TjxH0qsArjRvONT53++91aSljzt+LTeWgXKPzWX6qYMw1tYNuyOAVInMuB5EWpQB+RPRMgYKvGK0i71oWZIxzzkb0SmlX6yskY+MZnEQGV8qh57lYaxarf4onMn8GW/cG52UJWpb4QEbp39QyZtAhk6VO1hEXDPbtwsFgxTADhqcG2KB3z6jR6cbuX9bbtysl7Q1zV69BlV1vtFcsGoi5Y3Jx5/JGq3qcBv0+Pozj+TkDo5/xh93MaLCY8Tn0hvFBKL0e6GXkGI7MrhBtEI6JneQ7XKUjxSE2Be2eTk1jZN02Mye3iCwXZ6e46VyYE2hcqRrGPZ7bLtxuAaY7hp+ubtgqu7XJmjzfmG0O3rH9wpGIOnj55tt/j4JflnVEsojG9Ey6PRQgNissKTKpyLSbNKBGp4DhWtEvizDz7EuEU+pCyDilEFTH1EL/vSe4/VWhKxFfoHCZlI0vdW1NvbVEiy5H2ZI3xV1iVzf4Oh59OBJ+aVSEmCnV2YBWtVgRPAQjbXn8yFn2Swds0KGhGuDYbfjSJUKZrO348DTWpUmYI0Icg==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
