name: Update Image Tag

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Image Tag
        run: |
          sed -i 's/nginx:latest/nginx:1.25/' apps/nginx/deployment.yaml

      - name: Verify Changes
        run: |
          cat apps/nginx/deployment.yaml

      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          git add .

          git commit -m "Updated nginx image tag to 1.25" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main
